import Head from "next/head";
import { Inter } from "next/font/google";
import { GetServerSideProps } from "next";
import Article from "@/model/article.model";
import { useCallback, useEffect, useState } from "react";
import { articleRepo } from "../repository/article.repository";
import { PageWrapper } from "@/model/pageWrapper.model";
import ArticleList from "@/components/ArticleList";

const inter = Inter({ subsets: ["latin"] });

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { page = 1, limit = 6, searchKey, sort } = ctx.query;
  const data = articleRepo.getArticleWithFilter(
    page as number,
    limit as number,
    sort as string,
    searchKey as string
  );
  return {
    props: {
      data,
    },
  };
};

export default function Home({ data }: { data: PageWrapper<Article> }) {
  const [page, setPage] = useState<PageWrapper<Article>>(data);
  const setPageCallback = useCallback((page: PageWrapper<Article>) => {
    setPage(page);
  }, []);

  useEffect(() => {}, [data, page]);
  return (
    <>
      <Head>
        <title>KMB Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="  sm:mx-32">
          <ArticleList
            pageData={page}
            setPage={(newPage: PageWrapper<Article>) =>
              setPageCallback(newPage)
            }
          />
        </div>
      </main>
    </>
  );
}
